config/routes.rb
Rails.application.routes.draw do

  get 'projects/index'

  root 'welcome#index'

  get '/terms', to: 'terms#index'

  get '/about', to: 'about#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new'

  post 'sign-up', to: 'registrations#create'

  get 'sign-in', to: 'authentication#new'

  post 'sign-in', to: 'authentication#create'

  get 'sign-out', to: 'authentication#destroy'

  resources :pivotal_tracker, only: [:index]

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships, only: [:index, :create, :update, :destroy]
  end


end

app/models/membership.rb
class Membership < ActiveRecord::Base
  ROLES = ['Member', 'Owner']
  validates :user, presence: true
  validates :role, presence: true, inclusion: ROLES
  validates :user, uniqueness: { scope: :project,
    message: "has already been added to this project" }

  belongs_to :user
  belongs_to :project

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_action :check_current_user
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :check_member
  before_action :find_member, only: [:edit, :update ]
  before_action :count_owners
  before_action :verify_min_one_owner_update, only: [:edit, :update]
  before_action :verify_min_one_owner_destroy, only: [:destroy]

  def index
    @membership = @project.memberships.new
    @current_membership = current_user.memberships.find_by(project_id: @project.id)
  end

  def create
    @membership = @project.memberships.new(memberships_params)
    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was added successfully"
    else
      render :index
    end
  end

  def show
  end

  def edit
  end

  def update
    @membership = @project.memberships.find(params[:id])
    if @membership.update(params.require(:membership).permit(:role))
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was updated successfully"
    else
      redirect_to projects_path
    end
  end

  def destroy
    membership = Membership.find(params[:id])
    membership.destroy
    redirect_to projects_path, notice: "#{membership.user.full_name} successfully removed"
  end

  private
  def memberships_params
    params.require(:membership).permit(:user_id, :role)
  end

  def check_current_user
    if current_user
      @user = current_user
    else
      session[:redirect_to] = request.fullpath
      redirect_to sign_in_path, alert: "You must sign in"
    end
  end

  def check_member
    if !(current_user.memberships.find_by(project_id: @project.id) == nil) || current_user.admin

    else
      flash[:alert] = 'You do not have access to that project'
      redirect_to projects_path
    end
  end

  def find_member
    @current_membership = current_user.memberships.find_by(project_id: @project.id)
      if @current_membership.role == "Owner" || @user.admin == true

      else
        flash[:alert] = 'You do not have access'
        redirect_to project_path(@project)
    end
  end

  def count_owners
    owner_array = []
    owner_array << @project.memberships.find_by(role: "Owner")
    @owner_num = owner_array.count
  end

  def verify_min_one_owner_destroy
    if @current_membership.present?
      if @current_membership.role == "Owner" && @owner_num <= 1
        redirect_to project_memberships_path(@current_membership.project_id), alert: "Projects must have at least one owner"
      end
    end
  end

  def verify_min_one_owner_update
    if @current_membership.present?
      if @current_membership.role == "Owner" && (@project.memberships.where(role: "Owner").count <= 1)
        redirect_to project_memberships_path(@current_membership.project_id), alert: "Projects must have at least one owner"
      else

      end
    end
  end


end

app/views/memberships/_form.html.haml
.col-md-7.well
  = form_for([@project, @membership], html: {class: "form-inline"}) do |f|
    =f.collection_select(:user_id, User.all, :id, :full_name, {prompt: "Please select a user"}, {class: "form-control"})
    =f.collection_select(:role, Membership::ROLES, :to_s, :to_s, {}, class: "form-control")
    =f.submit 'Add New Member', class: "btn btn-primary"

app/views/memberships/index.html.haml
.container
  .page-header
    %h3= @project.name + ': Manage Members'
  %ol.breadcrumb
    %li= link_to 'Projects', projects_path
    %li= link_to @project.name, project_path(@project)
    %li Memberships
  %row
    -if @membership.errors.any?
      .alert.alert-danger.col-md-7
        %h3 #{pluralize((@membership.errors.size),'error')} prohibited this form from being saved:
        - @membership.errors.full_messages.each do |msg|
          %ul
            %li= msg
  -if !(current_user.admin)
    -if @current_membership.role == "Owner"
      = render 'form'
      .col-md-7
        %table.table
          %tbody
            -@project.memberships.each do |membership|
              -if membership.id
                %tr
                  = form_for([@project, membership], html: {class: "form-inline"}) do |f|
                    %td=link_to membership.user.full_name, user_path(membership.user)
                    %td=f.collection_select(:role, Membership::ROLES, :to_s, :to_s, {prompt: membership.role}, class: "form-control")
                    %td=f.submit 'Update Member', class: "btn btn-primary"
                    -if (membership.role == "Owner") && (@project.memberships.where(role: "Owner").count <= 1)
                      %td You are the last owner
                    -else
                      %td=link_to ' ' ,project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"
    -elsif @current_membership.role == "Member"
      .col-md-7
        %table.table
          %tbody
            -@project.memberships.each do |membership|
              -if membership.id
                %tr
                  = form_for([@project, membership], html: {class: "form-inline"}) do |f|
                    %td=link_to membership.user.full_name, user_path(membership.user)
                    %td=membership.role
                    -if current_user.id == membership.user_id
                      %td=link_to ' ' ,project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"
                    -else
                      %td

  -if current_user.admin
    = render 'form'
    .col-md-7
      %table.table
        %tbody
          -@project.memberships.each do |membership|
            -if membership.id
              %tr
                = form_for([@project, membership], html: {class: "form-inline"}) do |f|
                  %td=link_to membership.user.full_name, user_path(membership.user)
                  %td=f.collection_select(:role, Membership::ROLES, :to_s, :to_s, {prompt: membership.role}, class: "form-control")
                  %td=f.submit 'Update Member', class: "btn btn-primary"
                  -if (membership.role == "Owner") && (@owner_num <= 1)
                    %td You are the last owner
                  -else
                    %td=link_to ' ' ,project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"