config/routes.rb
Rails.application.routes.draw do

  get 'projects/index'

  root 'welcome#index'

  get '/terms', to: 'terms#index'

  get '/about', to: 'about#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new'

  post 'sign-up', to: 'registrations#create'

  get 'sign-in', to: 'authentication#new'

  post 'sign-in', to: 'authentication#create'

  get 'sign-out', to: 'authentication#destroy'

  resources :pivotal_tracker, only: [:index]

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships, only: [:index, :create, :update, :destroy]
  end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :description, presence: true

  belongs_to :user
  belongs_to :task

  def time_ago_in_words
    time_ago = (Time.now - self.created_at)/60
    "#{time_ago.to_i} minutes ago"
  end
end

app/models/common_questions.rb
class CommonQuestions

  def initialize(question, answer, slug)

  @question = question
  @answer = answer
  @slug = slug

  end



end

app/models/membership.rb
class Membership < ActiveRecord::Base
  ROLES = ['Member', 'Owner']
  validates :user, presence: true
  validates :role, presence: true, inclusion: ROLES
  validates :user, uniqueness: { scope: :project,
    message: "has already been added to this project" }

  belongs_to :user
  belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true
  belongs_to :project
  has_many :comments, dependent: :destroy

end

app/models/tracker_api.rb
class TrackerAPI

  def initialize
    @conn = Faraday.new(:url => 'https://www.pivotaltracker.com')
  end

  def projects(token)
    response = @conn.get do |req|
      req.url "/services/v5/projects"
      req.headers['Content-Type'] = 'application/json'
      req.headers['X-TrackerToken'] = token
    end
    JSON.parse(response.body, symbolize_names: true)
  end

  def stories(token, project_id)
    response = @conn.get do |request|
      request.url "/services/v5/projects/#{project_id}/stories"
      request.headers['Content-Type'] = 'application/json'
      request.headers['X-TrackerToken'] = token
    end
    JSON.parse(response.body, symbolize_names: true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_secure_password

  has_many :memberships, dependent: :destroy
  has_many :projects, through: :memberships
  has_many :comments

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end

  def set_user_id_nil_on_comments
    self.comments.update_all(user_id: nil)
  end

  def project_member_of(user)
    user.projects.map(&:users).flatten.include?(self)
  end

  def display_token
    self.tracker_token[0..3] + ('*'*(self.tracker_token.length - 4))
  end
end

app/controllers/about_controller.rb
class AboutController < PublicController

  def index
    @project = Project.all.count
    @task = Task.all.count
    @membership = Membership.all.count
    @user = User.all.count
    @comment = Comment.all.count
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action do
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @user = User.find(current_user)
  end

    def create
      @comment = @task.comments.new(comment_params)
      @comment.update_attributes(user_id: @user.id)
      if @comment.save
        redirect_to project_task_path(@project, @task)
      else
        redirect_to project_task_path(@project, @task)
      end
    end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error404
    render status: :not_found
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :check_current_user
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :check_member, only: [:index, :show, :edit, :update, :destroy]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = @project.tasks.new(tasks_params)
     if @task.save
       redirect_to project_tasks_path(@project, @task), notice: 'Task was successfully created.'
     else
       render :new
     end

  end

  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if  @task.update(tasks_params)
        redirect_to project_task_path, notice: 'Task was successfully updated'
    else
        render :edit
    end

  end

  def destroy
    task = @project.tasks.find(params[:id])
    task.destroy
    redirect_to project_tasks_path(@project), notice: "Task was successfully deleted."
  end

  private

  def tasks_params
    params.require(:task).permit(:description, :completed, :due_date)
  end

  def check_current_user
    if current_user
      @user = current_user
    else
      session[:redirect_to] = request.fullpath
      redirect_to sign_in_path, alert: "You must sign in"
    end
  end

  def check_member
    if !(current_user.memberships.find_by(project_id: @project.id) == nil) || current_user.admin

    else
      flash[:alert] = 'You do not have access to that project'
      redirect_to projects_path
    end
  end

end

app/controllers/terms_controller.rb
class TermsController < PublicController


  def index
  end
end

app/controllers/users_controller.rb
class UsersController<ApplicationController

  before_action :check_current_user

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
     if @user.save
       redirect_to users_path, notice: 'User was successfully created.'
     else
       render :new
     end

  end

  def show

    @user = User.find(params[:id])
    user = @user
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.id == @user.id || current_user.admin
      raise AccessDenied
    end
  end

  def update
    @user = User.find(params[:id])

    if  @user.update(users_params)
        redirect_to users_path, notice: 'User was successfully updated'
    else
        render :edit
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to users_path, notice: 'User was successfully deleted'
  end

  private

  def users_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin, :tracker_token)
  end

  def check_current_user
    if current_user

    else
      session[:redirect_to] = request.fullpath
      redirect_to sign_in_path, alert: "You must sign in"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < PublicController

  def index
    @quotesArray = [
        {author: "-Cayla Hayes", quote: "gCamp has changed my life! It's the best tool I've ever used."},
        {author: "-Leta Jaskolski", quote: "Before gCamp I was a disorderly slob. Now I'm more organized than I've ever been" },
        {author: "-Laverne Upton", quote: "Don't hesitate - Sign up right now!"}
      ]
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reece_helper.rb
module ReeceHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.haml
.container
  .page-header
    %h1 About
  .row
    .col-md-4
      = image_tag('aboutPic.jpg', class: "img-responsive")
    .col-md-8
      %p We are dedicated to the makers, the creators, the risk-takers.
      %p We wake up in the middle of the night and furiously write down ideas about how to make your online life better.
      %p Human collaboration and communication is what drives us, and it infuses every feature of gCamp.
  %h4 gCamp is extremely active. Check out our killer stats below!
  %h4="#{pluralize(@project, 'Project')}, #{pluralize(@task, 'Task')}, #{pluralize(@membership, 'Project Member')}, #{pluralize(@user, 'User')}, #{pluralize(@comment, 'Comment')}"

app/views/tasks/_form.html.haml
.container
  = form_for([@project, @task], html: {class: "form-horizontal"}) do |f|
    .form-group
      .col-sm-offset-2.col-sm-8
        = render partial: 'shared/errors', locals: { error: @task}
    .form-group
      %label.col-sm-2.control-label Description
      .col-sm-6
        = f.text_field :description, class: "form-control"
    .form-group
      %label.col-sm-2.control-label Due Date
      .col-sm-3
        = f.date_field :due_date, class: "form-control"
    .form-group
      .col-sm-offset-2.col-sm-10
        .checkbox
          - if @task.id
            %label
              = f.check_box :completed
              Completed
    .button.col-sm-offset-2
      = f.submit class: "btn btn-primary"
      = link_to 'Cancel', project_tasks_path, class: "btn btn-default"

app/views/tasks/edit.html.haml
.container
  .page-header
    %h1
      Edit Task
      %h1
  %ol.breadcrumb
    %li= link_to @project.name, project_path(@project)
    %li= link_to 'Tasks', project_tasks_path(@project, @task)
    %li= link_to @task.description, project_task_path(@project, @task)
    %li Edit Task
  = render "form"

app/views/tasks/index.html.haml
.container
  .page-header
    .pull-right
      = link_to 'New Task', new_project_task_path, class: "btn btn-info"
    %h1 Tasks for #{@project.name}
  %ol.breadcrumb
    %li= link_to 'Projects', projects_path
    %li= link_to @project.name, project_path(@project)
    %li Tasks
  %table.table
    %thead
      %th Description
      %th Due On
    %tbody
      - @project.tasks.each do |task|
        %tr
          %td.col-md-3
            - if task.completed
              %strike= link_to task.description, project_task_path(@project, task)
            - else
              = link_to task.description, project_task_path(@project, task)
            .badge= task.comments.count
          %td
            - if task.due_date
              = task.due_date.strftime("%m/%d/%y")
          %td
            .text-right
              = link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info"
              = link_to ' ', project_task_path(@project, task), method: :delete, class: "glyphicon glyphicon-remove"

app/views/tasks/new.html.haml
.container
  .page-header
    %h3
      New Task
      %h3
  %ol.breadcrumb
    %li= link_to @project.name, project_path(@project)
    %li= link_to 'Tasks', project_tasks_path
    %li New Task
  = render "form"

app/views/tasks/show.html.haml
.container
  .page-header
    .pull-right
      = link_to 'Edit', edit_project_task_path(@project, @task), class:"btn btn-info"
    - if @task.completed
      %h1
        %strike= @task.description
    - else
      %h1
        = @task.description
        %h1
  .row
    .col-sm-12
      %ol.breadcrumb
        %li= link_to 'Projects', projects_path
        %li= link_to @project.name, project_path(@project)
        %li= link_to 'Tasks', project_tasks_path(@project, @task)
        %li= @task.description
  %div
    %strong Due On:
    = @task.due_date.strftime("%m/%d/%y")

  %h3 Comments
  -@task.comments.each do |comment|
    .row
      .col-md-3
        -if comment.user
          =link_to comment.user.full_name, user_path(comment.user)
        -else
          ='(deleted user)'
        .text-muted= comment.time_ago_in_words
      .col-md-9
        =comment.description

  .form-horizontal
    =form_for([@project, @task, @comment], html: {class: "form-horizontal"}) do |f|
      .form-group
        .col-md-offset-3.col-md-9
          =f.text_area :description, class: "form-control"
      .form-group
        .col-md-offset-3.col-md-9
          =f.submit 'Add Comment', class: "btn btn-primary"

app/views/users/_form.html.haml
.container
  = form_for(@user, html: {class: "form-horizontal"}) do |f|
    .form-group
      .col-sm-offset-2.col-sm-8
        = render partial: 'shared/errors', locals: { error: @user}
    .form-group
      %label.col-sm-2.control-label First Name
      .col-sm-6
        = f.text_field :first_name, class: "form-control"
    .form-group
      %label.col-sm-2.control-label Last Name
      .col-sm-6
        = f.text_field :last_name, class: "form-control"
    .form-group
      %label.col-sm-2.control-label{:for => "inputEmail3"} Email
      .col-sm-6
        = f.email_field :email, class: "form-control"
    .form-group
      %label.col-sm-2.control-label Password
      .col-sm-6
        = f.password_field :password, class: "form-control"
    .form-group
      %label.col-sm-2.control-label Password Confirmation
      .col-sm-6
        = f.password_field :password_confirmation, class: "form-control"
    .form-group
      %label.col-sm-2.control-label Pivotal Tracker Token
      .col-sm-6
        = f.text_field :tracker_token, class: "form-control"
    -if current_user.admin
      .form-group
        %label.col-sm-2.control-label Admin
        .col-sm-6
          = f.check_box :admin, class: "form-control"
    .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"
      = link_to 'Cancel', users_path, class: "btn btn-default"
    .form-group
      .col-sm-offset-2.col-sm-6
        - if @user.id
          .well
            .text-center
              = link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/users/edit.html.haml
.container
  .page-header
    %h1 Update User  
  = render "form"

app/views/users/index.html.haml
.container
  .page-header
    .pull-right
      = link_to 'New User', new_user_path, class: "btn btn-info"
    %h1 Users
  %table.table
    %thead
      %tr
        %th Name
        %th Email
        %th
    -if current_user.admin
      - @users.each do |user|
        %tr
          %td
            =link_to user.first_name + ' ' + user.last_name, user_path(user)
          %td
            =mail_to user.email
          %td.text-right
            =link_to 'Edit', edit_user_path(user)
    -else
      -@users.each do |user|
        %tr
          %td
            =link_to user.first_name + ' ' + user.last_name, user_path(user)
          -if current_user.id == user.id || current_user.project_member_of(user)
            %td
              =mail_to user.email
            -if current_user.id == user.id
              %td
                =link_to 'Edit', edit_user_path(user)
            -else
              %td
          -else
            %td
            %td

app/views/users/new.html.haml
.container
  .page-header
    %h1 New User
  = render "form"

app/views/users/show.html.haml
.container
  .page-header
    .pull-right
      -if current_user.id == @user.id || current_user.admin
        = link_to 'Edit', edit_user_path(@user), class:"btn btn-info"
    %div
      %h1= @user.first_name + ' ' + @user.last_name
  %dl.dl-horizontal
    %dt
      First Name:
      %dd
        = @user.first_name
    %dt
      Last Name:
      %dd= @user.last_name
    %dt
      Email:
      %dd= mail_to @user.email
    -if current_user.tracker_token.present?
      %dt
        Pivotal Tracker Token:
        %dd= current_user.display_token

app/views/welcome/index.html.haml
.container
  .jumbotron
    %h1 gCamp
    %p your life, organized.
  .row
    .col-md-4
      %p.lead
        = image_tag("Pic1.jpg", class:"img-responsive")
    .col-md-4
      %p.lead
        = image_tag("Pic2.jpg", class:"img-responsive")
    .col-md-4
      %p.lead
        = image_tag("Pic3.jpg", class:"img-responsive")
  .row
    .col-md-4
      .panel.panel-default.panel-primary
        .panel-heading
          %h3.panel-title
            %strong Tasks
        .panel-body
          Grouped by projects and lists. Just the way you like'em.
    .col-md-4
      .panel.panel-default.panel-primary.panel-responsive
        .panel-heading
          %h3.panel-title
            %strong Permissions
        .panel-body
          Fine-Grained permissions.
    .col-md-4
      .panel.panel-default.panel-primary
        .panel-heading
          %h3.panel-title
            %strong Comments
        .panel-body
          %ul
            %li Comment on tasks and documents
            %li Get e-mail notifications
  .quotes
    %p
      "#{@quotesArray[0][:quote]}"
    %p.text-muted
      %em= @quotesArray[0][:author]
    %p
      "#{@quotesArray[1][:quote]}"
    %p.text-muted
      %em= @quotesArray[1][:author]
    %p
      "#{@quotesArray[2][:quote]}"
    %p.text-muted
      %em= @quotesArray[2][:author]