config/routes.rb
Rails.application.routes.draw do

  get 'projects/index'

  root 'welcome#index'

  get '/terms', to: 'terms#index'

  get '/about', to: 'about#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new'

  post 'sign-up', to: 'registrations#create'

  get 'sign-in', to: 'authentication#new'

  post 'sign-in', to: 'authentication#create'

  get 'sign-out', to: 'authentication#destroy'

  resources :pivotal_tracker, only: [:index]

  resources :users

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships, only: [:index, :create, :update, :destroy]
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :check_current_user
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :check_member, only: [:show, :edit, :update, :destroy]
  before_action :find_member, only: [:edit, :update, :destroy]


  def index
    @projects = Project.all
    if current_user.tracker_token.present?
      tracker_api = TrackerAPI.new
      @tracker_projects = tracker_api.projects(current_user.tracker_token)
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(projects_params)
    if @project.save
      @project.memberships.create(user_id: current_user.id, role: "Owner")
      redirect_to project_tasks_path(@project), notice: "Project was created successfully"
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @project.update(projects_params)
      redirect_to project_path(@project), notice: "Project was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: "Project was deleted successfully"
    end
  end

  private

  def projects_params
    params.require(:project).permit(:name)
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def check_current_user
    if current_user
      @user = current_user
    else
      session[:redirect_to] = request.fullpath
      redirect_to sign_in_path, alert: "You must sign in"
    end
  end

  def check_member
    @current_membership = current_user.memberships.find_by(project_id: @project.id)
    if !(current_user.memberships.find_by(project_id: @project.id) == nil) || current_user.admin

    else
      flash[:alert] = 'You do not have access to that project'
      redirect_to projects_path
    end
  end

  def find_member
    if !(current_user.admin)
      @current_membership = current_user.memberships.find_by(project_id: @project.id)
      if @current_membership.role == "Owner"

      else
        flash[:alert] = 'You do not have access'
        render :show
      end
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.container
  = form_for(@project, html: {class: "form-horizontal"}) do |f|
    .form-group
      .col-sm-offset-2.col-sm-8
        = render partial: 'shared/errors', locals: { error: @project}
    .form-group
      %label.col-sm-2.control-label Name
      .col-sm-6
        = f.text_field :name, class: "form-control"
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: "btn btn-primary"
        = link_to 'Cancel', projects_path, class: "btn btn-default"

app/views/projects/edit.html.haml
.container
  .page-header
    %h1 Edit Project
  %ol.breadcrumb
    %li= link_to 'Projects', projects_path
    %li= link_to @project.name, project_path(@project)
    %li Edit
  = render 'form'

app/views/projects/index.html.haml
.container
  .page-header
    .pull-right
      = link_to 'New Project', new_project_path, class: "btn btn-info"
    %h1 Projects
  %table.table
    %thead
      %tr
        %th Name
        %th Tasks
    - if current_user.admin
      - @projects.each do |project|
        %tr
          %td
            = link_to project.name, project_path(project)
          %td
            = link_to project.tasks.count, project_tasks_path(project)
    - else
      - @user.projects.each do |project|
        %tr
          %td
            = link_to project.name, project_path(project)
          %td
            = link_to project.tasks.count, project_tasks_path(project)
  -if current_user.tracker_token.present?
    %h1 Pivotal Tracker Projects
    %table.table
      %thead
        %tr
          %th Name
        - @tracker_projects.each do |project|          
          %tr
            %td
              =link_to project[:name], pivotal_tracker_index_path(project[:id], project_name: project[:name])

app/views/projects/new.html.haml
.container
  .page-header
    %h1
      New Project
      %h1
  %ol.breadcrumb
    %li= link_to 'Projects', projects_path
    %li New Project
  = render "form"

app/views/projects/show.html.haml
.container
  .page-header
    .pull-right
      -if !(current_user.admin)
        -unless @current_membership.role == "Member"
          = link_to 'Edit', edit_project_path(@project), class: "btn btn-primary"
      -else
        = link_to 'Edit', edit_project_path(@project), class: "btn btn-primary"
    %h1
      = @project.name
  %ol.breadcrumb
    %li= link_to 'Projects', projects_path
    %li= @project.name
  %br= link_to pluralize((@project.tasks.count),'task'), project_tasks_path(@project)
  %br= link_to pluralize((@project.memberships.count), 'member'), project_memberships_path(@project)

  -if !(current_user.admin)
    -unless @current_membership.role == "Member"
      .well
        %h4 Delete Project
        %p="Deleting this project will also delete #{pluralize(@project.memberships.count, 'membership')}, #{pluralize(@project.tasks.count, 'task')} and associated comments."
        %p=link_to "Delete", project_path(@project), method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure?'}